version: '3.9'
services:
  dbshard0:
    container_name: shard0
    image: bitnami/mysql:8.0.40
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - SHARD_DB=shard0
    volumes:
      - ./db/init.sql:/db/init.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
  dbshard1:
    container_name: shard1
    image: bitnami/mysql:8.0.40
    ports:
      - 3311:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - SHARD_DB=shard1
    volumes:
      - ./db/init.sql:/db/init.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
  dbshard2:
    container_name: shard2
    image: bitnami/mysql:8.0.40
    ports:
      - 3312:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - SHARD_DB=shard2
    volumes:
      - ./db/init.sql:/db/init.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh